# Generated by Django 4.2.7 on 2026-04-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='laundry_house_name',
        ),
    ]
