# Generated by Django 4.2.7 on 2026-04-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_created_at_user_full_name_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
