# Generated by Django 4.2.7 on 2026-05-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_customer_settings_fields'),
        ('accounts', '0004_user_home_address'),
    ]

    operations = [
    ]
