# Generated by Django 4.2.7 on 2026-06-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_subscription_plans'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customernotification',
            new_name='accounts_cu_user_id_9ada2a_idx',
            old_name='accounts_cu_user_id_8e2f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='customersubscription',
            new_name='accounts_cu_status_6dd9b7_idx',
            old_name='accounts_cus_status_b1e200_idx',
        ),
        migrations.RenameIndex(
            model_name='customersubscription',
            new_name='accounts_cu_custome_b599c8_idx',
            old_name='accounts_cus_custome_452eb6_idx',
        ),
    ]
