# Generated by Django 4.2.7 on 2026-04-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='urgency',
            field=models.CharField(choices=[('regular', 'Regular'), ('urgent', 'Urgent')], default='regular', max_length=20),
        ),
    ]
