# Generated by Django 4.2.7 on 2026-04-25 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_order_detail_order_urgency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fua_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('partner_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=20)),
                ('fua_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('partner_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price List Entry',
                'verbose_name_plural': 'Price List',
                'ordering': ['cloth_name', 'size'],
            },
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_rider_i_cec2cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_0e92de_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fualaundry_commission',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_detail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='partner_earning',
        ),
        migrations.RemoveField(
            model_name='order',
            name='picked_up_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rider_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='rider_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('washing', 'Washing'), ('ready', 'Ready to Deliver'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('cloth_name', 'size')},
        ),
        migrations.AddField(
            model_name='clothitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth_items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='clothitem',
            name='price_list_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloth_items', to='orders.pricelist'),
        ),
    ]
