# Generated by Django 4.2.7 on 2026-04-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_clothitem_pricelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cloth_images'),
        ),
    ]
