# Generated by Django 4.2.7 on 2026-05-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_rider_accepted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the assigned rider confirmed the job and unlocked customer contact.', null=True),
        ),
    ]
