# Generated by Django 4.2.7 on 2026-05-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_rider_accepted_at'),
        ('orders', '0008_clothcategory'),
    ]

    operations = [
    ]
