# Generated by Django 4.2.7 on 2026-04-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundrypartner',
            name='commission_rate',
        ),
    ]
