# Generated by Django 4.2.7 on 2026-06-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial_customer_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='laundrylocation',
            new_name='core_laundr_is_acti_7a1f98_idx',
            old_name='core_laundr_is_acti_cdb470_idx',
        ),
        migrations.RenameIndex(
            model_name='testimonial',
            new_name='core_testim_is_appr_f20419_idx',
            old_name='core_testim_is_appr_c7606a_idx',
        ),
    ]
